# new file, with new attempt to create proper docker compose file #

version: "3.9"

services:

  to-do-app: 
  # if you wondering how i start 5 to-do-apps at the same time without changing docker-compose.yml, #
  # i used --scale command in terminal: (docker-compose up --scale to-do-app=5) #
    image: evansgreaper/devops-docker-repo
    expose: 
      - "5000"
    restart: always
    links: 
      - database

  database:
    image: postgres
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always

  java-app: # no idea what app to find, so i decided to try to run a whole minecraft server#
    image: itzg/minecraft-bedrock-server
    ports: 
    - "25565:25565"
    environment:
      EULA: 'true'
    links: 
      - database
    restart: always  