version: "3.9"  # optional since v1.27.0
services:
db:
  image: postgres: 12.5-alpine
  web:
    build: .
    ports: 
      - "5000:5000"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pg_data
      - .:/code
      - logvolume01:/var/log
    environment: 
    POSTGRES_PASSWORD: 12344
    POSTGRES_DB: DOCKER_TEST_DB
    PGDATA: /var/lib/postgresql/data/pg_data
    restart: always

app:
  image: evansgreaper/devops-docker-repo #image i already have at my dockerhub
  container_name: application
    ports: 
      - "3000:3000"
    environment: 
    POSTGRES_HOST: db
    restart: always


    links:
      - db
nginx: 
  image: nginx: 1.19.6-alpine
  container_name: nginx
  volumes: 
    - ./default.conf:/etc/nginx/conf.d/default.conf
    links: 
      - app
