# I'm trying to start postgres databases #

version: "3.9"

services: 

 db_master: 
  image: postgres
  env_file: 
   - database.env
  volumes: 
   - database-data:/var/lib/postgres/data/ 
  ports:
   - "5433:5433"
  restart: always

 db_replica: 
  image: postgres
  env_file: 
  - database.env
  volumes: 
  - database-data:/var/lib/postgres/data/ 
  ports:
  - "5432:5432"
  restart: always

volumes: 
  database-data: