# I'm trying to start postgres database #

version: "3.9"

services: 

  db: 
    image: postgres
    env_file: 
     - database.env
    volumes: 
     - database-data:/var/lib/postgresql/data/ 
    ports:
     - "5432:5432"
    restart: always

volumes: 
  database-data: